import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],


  algorithm: [{ type: 'autogenerated', dirName: 'algorithm' }],
  java: [{ type: 'autogenerated', dirName: 'java' }],
  framework: [{ type: 'autogenerated', dirName: 'framework' }],
  design: [{ type: 'autogenerated', dirName: 'design' }],
  middleware: [{ type: 'autogenerated', dirName: 'middleware' }],
  language: [{ type: 'autogenerated', dirName: 'language' }],
  webApp: [
    'web/hello',
    /* {
      type: 'category',
      label: 'Web应用',
      items: ['web/hello'],
    }, */
  ],
  operations: [{ type: 'autogenerated', dirName: 'operations' }],
  tools: [{ type: 'autogenerated', dirName: 'tools' }],
  cyber: [{ type: 'autogenerated', dirName: 'cyber' }],
  rust: [{ type: 'autogenerated', dirName: 'rust' }],
  tips: [{ type: 'autogenerated', dirName: 'tips' }],
  // language: [
  //   'hello',
  //   {
  //     type: 'category',
  //     label: '编程语言',
  //     items: ['tutorial-basics/create-a-document'],
  //   },
  // ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  workout: [{ type: 'autogenerated', dirName: 'workout' }],
  plan: [{ type: 'autogenerated', dirName: 'plan' }],
};

export default sidebars;
