version: 7
profiles:
  - type: ssh
    name: '180'
    icon: fas fa-desktop
    options:
      host: ''
      user: dataaware
      algorithms: {}
      input: {}
      auth: password
    weight: -1
    id: ssh:custom:180:13ca640c-fd80-4ab9-9548-d267e07277dd
  - type: ssh
    name: vm1-ubuntu20
    icon: fas fa-desktop
    options:
      host: 192.168.190.128
      user: dev
      algorithms: {}
      input: {}
      privateKeys: []
    weight: -1
    id: ssh:custom:vm1-ubuntu20-copy:46a30ba6-d2b4-4a39-8a29-0167d93d7063
  - type: ssh
    name: vm3-ubuntu20
    icon: fas fa-desktop
    options:
      host: 192.168.190.130
      user: dev
      algorithms: {}
      input: {}
      privateKeys: []
    weight: -1
    id: ssh:custom:vm2:365193f5-928a-4d1f-b2cf-877459877894
  - type: ssh
    icon: fas fa-desktop
    options:
      host: 10.26.20.118
      user: dataaware
      algorithms: {}
      input: {}
      auth: password
    weight: -1
    name: '118'
    id: ssh:custom:118:507bae83-8992-4927-8553-44a511ac1c73
    group: 8ed42e88-7386-4c7e-a12f-fe69e3a85874
  - type: ssh
    icon: fas fa-desktop
    options:
      host: 10.26.20.120
      user: dataaware
      algorithms: {}
      input: {}
      auth: password
      port: 22122
    weight: -1
    group: 8ed42e88-7386-4c7e-a12f-fe69e3a85874
    name: '120'
    id: ssh:custom:120:abc2dda4-4edb-40e3-8d11-3fe36b2ddcdc
  - type: ssh
    icon: fas fa-desktop
    options:
      host: 10.26.20.121
      user: dataaware
      algorithms: {}
      input: {}
      auth: password
      port: 22122
    weight: -1
    group: 8ed42e88-7386-4c7e-a12f-fe69e3a85874
    name: '121'
    id: ssh:custom:120-copy:eb72d878-4e32-4fa6-af14-57ed081276f5
  - type: ssh
    icon: fas fa-desktop
    options:
      host: 10.26.20.122
      user: dataaware
      algorithms: {}
      input: {}
      auth: password
    weight: -1
    group: 8ed42e88-7386-4c7e-a12f-fe69e3a85874
    name: '122'
    id: ssh:custom:122:cf580d94-7df7-40ce-b56a-3d8f601f7a7a
  - type: ssh
    icon: fas fa-desktop
    options:
      host: 118.190.39.100
      algorithms: {}
      input: {}
      port: 19220
      auth: password
    weight: -1
    group: 7e5a290e-8e22-414f-90aa-9410fc302cc3
    name: 118.190.39.100
    id: ssh:custom:118.190.39.100:f3fcc866-a029-4770-8c27-1028aa7cda4f
  - type: ssh
    name: 203.83.232.58
    icon: fas fa-desktop
    options:
      host: 203.83.232.58
      algorithms: {}
      input: {}
      auth: password
    weight: -1
    id: ssh:custom:203.83.232.58:217c34dd-b916-4b75-b199-f8d9a7b58f09
    group: 7e5a290e-8e22-414f-90aa-9410fc302cc3
  - type: ssh
    icon: fas fa-desktop
    options:
      host: 172.21.1.31
      user: test
      algorithms: {}
      input: {}
      privateKeys: []
    weight: -1
    group: 93ecf7bc-05da-4690-bc4d-fa7d92ed4c5f
    name: '31'
    id: ssh:custom:31:b06925a2-ed7d-434d-a795-810ab0e2d84e
  - type: ssh
    name: '58'
    icon: fas fa-desktop
    options:
      host: 172.21.1.58
      user: primihub
      algorithms:
        hmac:
          - hmac-sha1
          - hmac-sha1-etm@openssh.com
          - hmac-sha2-256
          - hmac-sha2-256-etm@openssh.com
          - hmac-sha2-512
          - hmac-sha2-512-etm@openssh.com
        kex:
          - curve25519-sha256
          - curve25519-sha256@libssh.org
          - diffie-hellman-group-exchange-sha256
          - diffie-hellman-group14-sha256
          - diffie-hellman-group15-sha512
          - diffie-hellman-group16-sha512
          - diffie-hellman-group17-sha512
          - diffie-hellman-group18-sha512
          - ecdh-sha2-nistp256
          - ecdh-sha2-nistp384
          - ecdh-sha2-nistp521
        cipher:
          - aes128-ctr
          - aes128-gcm
          - aes128-gcm@openssh.com
          - aes192-ctr
          - aes256-ctr
          - aes256-gcm
          - aes256-gcm@openssh.com
        serverHostKey:
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp384
          - ecdsa-sha2-nistp521
          - rsa-sha2-256
          - rsa-sha2-512
          - ssh-ed25519
          - ssh-rsa
      input: {}
      privateKeys: []
      forwardedPorts: []
      scripts: []
    weight: -1
    group: 93ecf7bc-05da-4690-bc4d-fa7d92ed4c5f
    id: ssh:custom:172.21.1.58:073cf16c-6167-483c-b71a-ecbf13ef3c4c
  - type: ssh
    name: '62'
    icon: fas fa-desktop
    options:
      host: 10.93.116.49
      user: primihub
      algorithms: {}
      input: {}
      privateKeys: []
    weight: -1
    group: 93ecf7bc-05da-4690-bc4d-fa7d92ed4c5f
    id: ssh:custom:172.21.1.62:e72e2ee3-c3c3-4527-833c-a4bc91d3c265
  - type: ssh
    name: '63'
    icon: fas fa-desktop
    options:
      host: 172.21.1.63
      user: primihub
      algorithms: {}
      input: {}
      privateKeys: []
    weight: -1
    group: 93ecf7bc-05da-4690-bc4d-fa7d92ed4c5f
    id: ssh:custom:172.21.1.62-copy:c82a63f4-d8e6-4c5e-afab-29c81bb652e5
  - type: ssh
    icon: fas fa-desktop
    options:
      host: 172.21.1.64
      user: primihub
      algorithms: {}
      input: {}
      privateKeys: []
    weight: -1
    group: 93ecf7bc-05da-4690-bc4d-fa7d92ed4c5f
    id: ssh:custom:172.21.1.62-copy-copy:29d2de1b-d904-4439-9d1d-bfad75e413cd
    name: '64'
  - type: ssh
    icon: fas fa-desktop
    options:
      host: 172.21.1.65
      user: primihub
      algorithms: {}
      input: {}
      privateKeys: []
    weight: -1
    group: 93ecf7bc-05da-4690-bc4d-fa7d92ed4c5f
    id: ssh:custom:172.21.1.62-copy-copy-copy:35261163-1fb8-44e5-972c-407bab1f8e30
    name: '65'
  - type: ssh
    icon: fas fa-desktop
    options:
      host: 10.93.116.212
      algorithms: {}
      input: {}
      auth: password
    weight: -1
    group: 781c7984-b2ec-414a-84d8-82cfad12cffe
    name: 10-harbor
    id: ssh:custom:10:ed72bc92-7ea5-4657-8c21-851c20d9b954
  - type: ssh
    icon: fas fa-desktop
    options:
      host: 10.93.116.98
      algorithms: {}
      input: {}
      auth: password
    weight: -1
    group: 781c7984-b2ec-414a-84d8-82cfad12cffe
    name: '11'
    id: ssh:custom:11:e024a2c8-7bcc-4f6c-8e3c-309a978490c0
  - type: ssh
    icon: fas fa-desktop
    options:
      host: 10.93.116.87
      algorithms: {}
      input: {}
      auth: password
      user: dell
    weight: -1
    name: '12'
    group: 781c7984-b2ec-414a-84d8-82cfad12cffe
    id: ssh:custom:11:3c0d5269-4e9c-4dc0-a050-6f0b251c20bf
  - type: ssh
    icon: fas fa-desktop
    options:
      host: 10.93.116.228
      algorithms: {}
      input: {}
      auth: password
    weight: -1
    name: '13'
    id: ssh:custom:13:f280f1b4-47e6-4282-9345-f9b591d86fc3
    group: 781c7984-b2ec-414a-84d8-82cfad12cffe
  - type: ssh
    icon: fas fa-desktop
    options:
      host: 192.168.99.14
      algorithms: {}
      input: {}
      auth: password
    weight: -1
    group: 781c7984-b2ec-414a-84d8-82cfad12cffe
    name: '14'
    id: ssh:custom:14:51771319-d149-43d6-8090-240b74360e90
  - type: ssh
    name: 14-vmware
    icon: fas fa-desktop
    options:
      host: 192.168.99.14
      algorithms: {}
      input: {}
      privateKeys: []
    weight: -1
    group: 781c7984-b2ec-414a-84d8-82cfad12cffe
    id: ssh:custom:14-vmware:c4313ddb-1824-4a09-a4bf-3e62b423fa72
  - type: ssh
    icon: fas fa-desktop
    options:
      host: 192.168.99.15
      algorithms: {}
      input: {}
      auth: password
    weight: -1
    name: '15'
    group: 781c7984-b2ec-414a-84d8-82cfad12cffe
    id: ssh:custom:15:8f1d4aff-7681-4759-9f99-8ce74dc9b44c
  - type: ssh
    icon: fas fa-desktop
    options:
      host: 192.168.99.16
      algorithms: {}
      input: {}
      auth: password
    weight: -1
    name: '16'
    group: 781c7984-b2ec-414a-84d8-82cfad12cffe
    id: ssh:custom:16:e0504fd6-87ff-4548-abb0-d03935fac1be
  - type: ssh
    icon: fas fa-desktop
    options:
      host: 192.168.99.18
      algorithms: {}
      input: {}
      auth: password
    weight: -1
    group: 781c7984-b2ec-414a-84d8-82cfad12cffe
    name: '18'
    id: ssh:custom:18:694a59c5-481e-4e7b-9fec-a8518e5d2557
  - type: ssh
    icon: fas fa-desktop
    options:
      host: 192.168.99.19
      algorithms:
        hmac:
          - hmac-sha1
          - hmac-sha1-etm@openssh.com
          - hmac-sha2-256
          - hmac-sha2-256-etm@openssh.com
          - hmac-sha2-512
          - hmac-sha2-512-etm@openssh.com
        kex:
          - curve25519-sha256
          - curve25519-sha256@libssh.org
          - diffie-hellman-group-exchange-sha256
          - diffie-hellman-group14-sha256
          - diffie-hellman-group15-sha512
          - diffie-hellman-group16-sha512
          - diffie-hellman-group17-sha512
          - diffie-hellman-group18-sha512
          - ecdh-sha2-nistp256
          - ecdh-sha2-nistp384
          - ecdh-sha2-nistp521
        cipher:
          - aes128-ctr
          - aes128-gcm
          - aes128-gcm@openssh.com
          - aes192-ctr
          - aes256-ctr
          - aes256-gcm
          - aes256-gcm@openssh.com
        serverHostKey:
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp384
          - ecdsa-sha2-nistp521
          - rsa-sha2-256
          - rsa-sha2-512
          - ssh-ed25519
          - ssh-rsa
      input: {}
      auth: password
      forwardedPorts: []
      scripts: []
    weight: -1
    name: '19'
    group: 781c7984-b2ec-414a-84d8-82cfad12cffe
    id: ssh:custom:18:91d5a1fc-dbce-4fc6-8f20-4d780139cf0e
  - type: ssh
    name: '21'
    icon: fas fa-desktop
    options:
      host: 192.168.99.21
      user: primihub
      algorithms: {}
      input: {}
      privateKeys: []
    weight: -1
    group: 781c7984-b2ec-414a-84d8-82cfad12cffe
    id: ssh:custom:21:e408a844-23fb-4f97-a943-8c5237665121
  - type: ssh
    name: '22'
    icon: fas fa-desktop
    options:
      host: 192.168.99.22
      user: primihub
      algorithms: {}
      input: {}
      privateKeys: []
    weight: -1
    id: ssh:custom:22:06bd4e26-a75d-492d-a058-017e56b91d4d
    group: 781c7984-b2ec-414a-84d8-82cfad12cffe
  - type: ssh
    name: '23'
    icon: fas fa-desktop
    options:
      host: 192.168.99.23
      user: primihub
      algorithms: {}
      input: {}
      privateKeys: []
    weight: -1
    group: 781c7984-b2ec-414a-84d8-82cfad12cffe
    id: ssh:custom:23:42b614ad-f1e6-45d5-9821-9fefc72b6778
  - type: ssh
    icon: fas fa-desktop
    options:
      host: 192.168.99.24
      user: primihub
      algorithms: {}
      input: {}
      privateKeys: []
    weight: -1
    group: 781c7984-b2ec-414a-84d8-82cfad12cffe
    name: '24'
    id: ssh:custom:24:675a2604-60eb-4399-8e5d-60c3d3c3f0ba
  - type: ssh
    icon: fas fa-desktop
    options:
      host: 192.168.99.26
      user: primihub
      algorithms: {}
      input: {}
    weight: -1
    group: 781c7984-b2ec-414a-84d8-82cfad12cffe
    name: '26'
    id: ssh:custom:26:5fe47c70-9b17-47c6-9962-13ff7db8a308
  - type: ssh
    icon: fas fa-desktop
    options:
      host: 192.168.99.27
      user: admin
      algorithms: {}
      input: {}
      privateKeys: []
    weight: -1
    group: 781c7984-b2ec-414a-84d8-82cfad12cffe
    name: '27'
    id: ssh:custom:26:d4158b78-57ea-4a12-bd7e-918435787b52
  - type: ssh
    icon: fas fa-desktop
    options:
      host: 10.93.116.17
      algorithms: {}
      input: {}
      privateKeys: []
    weight: -1
    name: '30'
    id: ssh:custom:30:e6c9f2b2-c3d5-4d88-86b6-0b64bc54f8b7
    group: 781c7984-b2ec-414a-84d8-82cfad12cffe
  - type: ssh
    icon: fas fa-desktop
    options:
      host: 10.93.116.34
      algorithms: {}
      input: {}
      privateKeys: []
    weight: -1
    group: 781c7984-b2ec-414a-84d8-82cfad12cffe
    name: '31'
    id: ssh:custom:31:a5c184ef-4108-4dba-9336-d557bb617ae5
  - type: ssh
    icon: fas fa-desktop
    options:
      host: 10.93.116.123
      algorithms: {}
      input: {}
      privateKeys: []
    weight: -1
    group: 781c7984-b2ec-414a-84d8-82cfad12cffe
    name: '32'
    id: ssh:custom:32:6efc00b2-2c61-4d57-bf8a-5e2abd2d09c1
  - type: ssh
    icon: fas fa-desktop
    options:
      host: 10.93.116.40
      user: primihub
      algorithms: {}
      input: {}
      privateKeys: []
    weight: -1
    group: 781c7984-b2ec-414a-84d8-82cfad12cffe
    name: '33'
    id: ssh:custom:33:f5677e26-d2e1-4d3a-9397-9ac51a585f91
  - type: ssh
    icon: fas fa-desktop
    options:
      host: 10.93.116.195
      user: primihub
      algorithms: {}
      input: {}
      privateKeys: []
    weight: -1
    group: 781c7984-b2ec-414a-84d8-82cfad12cffe
    name: 34 sgx
    id: ssh:custom:34:4fd81de1-3017-40b5-82b3-549975e3901f
groups:
  - id: 8ed42e88-7386-4c7e-a12f-fe69e3a85874
    name: dev
  - id: 781c7984-b2ec-414a-84d8-82cfad12cffe
    name: primihub
  - id: 93ecf7bc-05da-4690-bc4d-fa7d92ed4c5f
    name: office
  - id: 7e5a290e-8e22-414f-90aa-9410fc302cc3
    name: cloud
configSync:
  parts: {}
hotkeys:
  toggle-window:
    - Ctrl-Space
  copy-current-path: []
  ctrl-c:
    - Ctrl-C
  copy:
    - Ctrl-Shift-C
    - ⌘-C
  paste:
    - Ctrl-Shift-V
    - Shift-Insert
    - ⌘-V
  select-all:
    - Ctrl-Shift-A
  clear: []
  zoom-in:
    - Ctrl-=
    - Ctrl-Shift-=
  zoom-out:
    - Ctrl--
    - Ctrl-Shift--
  reset-zoom:
    - Ctrl-0
  home:
    - Home
  end:
    - End
  previous-word:
    - Ctrl-Left
  next-word:
    - Ctrl-Right
  delete-previous-word:
    - Ctrl-Backspace
  delete-line:
    - Ctrl-Shift-Backspace
  delete-next-word:
    - Ctrl-Delete
  search:
    - Ctrl-Shift-F
  pane-focus-all:
    - Ctrl-Shift-I
  focus-all-tabs:
    - Ctrl-Alt-Shift-I
  scroll-to-top:
    - Ctrl-PageUp
  scroll-up:
    - Alt-PageUp
  scroll-down:
    - Alt-PageDown
  scroll-to-bottom:
    - Ctrl-PageDown
  restart-telnet-session: []
  restart-ssh-session: []
  launch-winscp: []
  settings-tab: {}
  settings:
    - Ctrl-,
  serial:
    - Alt-K
  restart-serial-session: []
  new-tab:
    - Ctrl-Shift-T
  new-window:
    - Ctrl-Shift-N
  profile: {}
  profile-selectors: {}
  toggle-fullscreen:
    - F11
    - Alt-Enter
  close-tab:
    - Ctrl-W
  reopen-tab:
    - Ctrl-Shift-Z
  toggle-last-tab: []
  rename-tab:
    - Ctrl-Shift-R
  next-tab:
    - Ctrl-Shift-Right
    - Ctrl-Tab
  previous-tab:
    - Ctrl-Shift-Left
    - Ctrl-Shift-Tab
  move-tab-left:
    - Ctrl-Shift-PageUp
  move-tab-right:
    - Ctrl-Shift-PageDown
  rearrange-panes:
    - Ctrl-Shift
  duplicate-tab: []
  restart-tab: []
  reconnect-tab: []
  disconnect-tab: []
  explode-tab:
    - Ctrl-Shift-.
  combine-tabs:
    - Ctrl-Shift-,
  tab-1:
    - Alt-1
  tab-2:
    - Alt-2
  tab-3:
    - Alt-3
  tab-4:
    - Alt-4
  tab-5:
    - Alt-5
  tab-6:
    - Alt-6
  tab-7:
    - Alt-7
  tab-8:
    - Alt-8
  tab-9:
    - Alt-9
  tab-10:
    - Alt-0
  tab-11: []
  tab-12: []
  tab-13: []
  tab-14: []
  tab-15: []
  tab-16: []
  tab-17: []
  tab-18: []
  tab-19: []
  tab-20: []
  split-right:
    - Ctrl-Shift-S
  split-bottom:
    - Ctrl-Shift-D
  split-left: []
  split-top: []
  pane-nav-right:
    - Ctrl-Alt-Right
  pane-nav-down:
    - Ctrl-Alt-Down
  pane-nav-up:
    - Ctrl-Alt-Up
  pane-nav-left:
    - Ctrl-Alt-Left
  pane-nav-previous:
    - Ctrl-Alt-[
  pane-nav-next:
    - Ctrl-Alt-]
  pane-nav-1: []
  pane-nav-2: []
  pane-nav-3: []
  pane-nav-4: []
  pane-nav-5: []
  pane-nav-6: []
  pane-nav-7: []
  pane-nav-8: []
  pane-nav-9: []
  pane-maximize:
    - Ctrl-Alt-Enter
  close-pane:
    - Ctrl-Alt-W
    - Ctrl-Shift-W
  pane-increase-vertical: []
  pane-decrease-vertical: []
  pane-increase-horizontal: []
  pane-decrease-horizontal: []
  switch-profile:
    - Ctrl-Alt-T
  profile-selector:
    - Ctrl-Shift-E
  command-selector:
    - Ctrl-Shift-P
  scroll-page-up:
    - Alt-PageUp
  scroll-page-down:
    - Alt-PageDown
  group-selectors: {}
terminal:
  searchOptions: {}
  colorScheme:
    name: Arthur
    foreground: '#ddeedd'
    background: '#1c1c1c'
    cursor: '#e2bbef'
    colors:
      - '#3d352a'
      - '#cd5c5c'
      - '#86af80'
      - '#e8ae5b'
      - '#6495ed'
      - '#deb887'
      - '#b0c4de'
      - '#bbaa99'
      - '#554444'
      - '#cc5533'
      - '#88aa22'
      - '#ffa75d'
      - '#87ceeb'
      - '#996600'
      - '#b0c4de'
      - '#ddccbb'
  lightColorScheme:
    name: Tabby Default Light
    foreground: '#4d4d4c'
    background: '#ffffff'
    cursor: '#4d4d4c'
    colors:
      - '#000000'
      - '#c82829'
      - '#718c00'
      - '#eab700'
      - '#4271ae'
      - '#8959a8'
      - '#3e999f'
      - '#ffffff'
      - '#000000'
      - '#c82829'
      - '#718c00'
      - '#eab700'
      - '#4271ae'
      - '#8959a8'
      - '#3e999f'
      - '#ffffff'
  customColorSchemes: []
  font: JetBrains Mono
  copyAsHTML: false
  copyOnSelect: false
  profile: local:powershell
ssh:
  knownHosts:
    - host: 192.168.190.129
      port: 22
      type: ecdsa-sha2-nistp256
      digest: r8BmTkaVi2SmbAzgBXi15F1KAXAvaEOuFlX33Puu6sQ=
    - host: 192.168.190.130
      port: 22
      type: ecdsa-sha2-nistp256
      digest: q7YJANKZiSMCx374K461fwG4aibSArYUHEExX0a2FMQ=
    - host: 192.168.190.128
      port: 22
      type: ecdsa-sha2-nistp256
      digest: R+/XGx/lmZCrq6LdMSIarGa/OdQovKbHEgnPzIwUEWY=
    - host: 10.26.20.118
      port: 22
      type: ecdsa-sha2-nistp256
      digest: efz1YvOyN8RCPdJVvUKVdEmUo5oglEcn9r9F4AbzX7o=
    - host: 10.26.20.120
      port: 22122
      type: ecdsa-sha2-nistp256
      digest: qMmHt9QBICBmN94OmAJxaV3kcWMbWAPDehk8sn3h90I=
    - host: 10.26.20.121
      port: 22122
      type: ecdsa-sha2-nistp256
      digest: qMmHt9QBICBmN94OmAJxaV3kcWMbWAPDehk8sn3h90I=
    - host: 192.168.99.22
      port: 22
      type: ecdsa-sha2-nistp256
      digest: bC6z1iHh+28xB7JuKDqHFCk2QEoCTSZ4wM9tRZQvRNg=
    - host: 192.168.99.13
      port: 22
      type: ecdsa-sha2-nistp256
      digest: 506piwkOrNFlwp6bWHz4cRPLiOMHN4clu3sC4MC5N7w=
    - host: 192.168.99.23
      port: 22
      type: ecdsa-sha2-nistp256
      digest: x/LsFQhcAZlu2hAIezjzxNX367b7rQXrbAFnQPm9hzE=
    - host: 192.168.99.24
      port: 22
      type: ecdsa-sha2-nistp256
      digest: nQhrZ6rB41BMmDBkfe4cZUIGqWf5kVOO6hld+Jw9AB8=
    - host: 172.21.1.58
      port: 22
      type: ecdsa-sha2-nistp256
      digest: H6PIlC8QacCARKvz9Jr2bLuM+QCxLGUmXZiP6X6y+QA=
    - host: 192.168.99.33
      port: 22
      type: ecdsa-sha2-nistp256
      digest: 8mmJbaFHucwPYDMFwWnvBfZd5EX2ajCyCxx/gdZcoDU=
    - host: 192.168.99.46
      port: 22
      type: ecdsa-sha2-nistp256
      digest: gPU4hNiEIExOi/IB6XfSn/EHVH22AXBwekONZ+jAyXQ=
    - host: 192.168.99.26
      port: 22
      type: ecdsa-sha2-nistp256
      digest: KqJqfIZaNjXyvLGezCz/hsTX8odE1RzVhuzriN0fM/8=
    - host: 118.190.39.100
      port: 19220
      type: ecdsa-sha2-nistp256
      digest: nAwWXJ2gZ8iJoR612IOBFgHjbxPjmmfj7KCsjn4wX5s=
    - host: 192.168.99.11
      port: 22
      type: ecdsa-sha2-nistp256
      digest: 8NdBm8wiSaqflAalI2vSugul5RFyfw1vT5pgCc6K1hk=
    - host: 192.168.99.10
      port: 22
      type: ecdsa-sha2-nistp256
      digest: ozrYgpsTS0Bhg7riX9n9602uTOYXIplSuh3uwvCf0yo=
    - host: 192.168.99.30
      port: 22
      type: ecdsa-sha2-nistp256
      digest: kX6WOgIUO6AVqGSgKZZG/88JV65SlAiSD0T7pJhYVQY=
    - host: 39.98.95.214
      port: 22
      type: ecdsa-sha2-nistp256
      digest: utNsCEfBCRkr2ZMTEzvGVZG1EzsgOIkB7eUw92itV8g=
    - host: 172.21.1.62
      port: 22
      type: ecdsa-sha2-nistp256
      digest: c7aeaLZwMPGrRuOIc7E8WSz7hlaR2in/AHzZql/mHso=
    - host: 172.21.1.63
      port: 22
      type: ecdsa-sha2-nistp256
      digest: ZBDU+704jObe85ylWNYobZsgsAjIzhIh8JmyPd1jIgA=
    - host: 172.21.1.64
      port: 22
      type: ecdsa-sha2-nistp256
      digest: mV65lXzxU4jJac2xelZQ057xu3iMxzPo4tC0BuWQNrE=
    - host: 172.21.1.65
      port: 22
      type: ecdsa-sha2-nistp256
      digest: w5ERZjPllBrSYrGOs9XJyOxeG5xvLPc3dElGge3FGmU=
    - host: 192.168.99.15
      port: 22
      type: ecdsa-sha
clickableLinks: {}
accessibility: {}
appearance: {}
hacks: {}
pluginBlacklist: []
providerBlacklist: []
profileDefaults:
  ssh:
    disableDynamicTitle: true
profileBlacklist: []
